# 0.0 Pytroch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Introduction to tensors

Creating tensors

In [ ]:
#Scalar
scalar =torch.tensor(7)
scalar

tensor(7)

In [ ]:
#Features of tensors
scalar.ndim

0

In [ ]:
#Get tensor back as python int
scalar.item()

7

In [ ]:
#Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
#Shape> Basicamente, una matrix de 2*2 te dara 2,2. Y asi con tensores mas
#grandes.
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX=torch.tensor([[7,8],[3,2]])
MATRIX

tensor([[7, 8],
        [3, 2]])

In [ ]:
#Basicamente, piensa en dim como en el numero de corchetes que tienes! Xd
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR=torch.tensor([[[3,4,3],
                      [5,6,1],
                      [5,6,2]],
                            [[3,2131,3],
                            [5,6,1],
                            [5,6,512]]])
TENSOR

tensor([[[   3,    4,    3],
         [   5,    6,    1],
         [   5,    6,    2]],

        [[   3, 2131,    3],
         [   5,    6,    1],
         [   5,    6,  512]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[1]

tensor([[   3, 2131,    3],
        [   5,    6,    1],
        [   5,    6,  512]])

## Random Tensors

Why?

Many neuro networks start with tensors of random numbers and then they ajust those random numbers!
"Start Random Numbers->Look at data->Update random numbers->look at data->update..."

In [ ]:
# Create a random tensor
random_tensor=torch.rand(1,3,4)
random_tensor

tensor([[[0.9724, 0.3644, 0.9575, 0.7980],
         [0.4580, 0.1651, 0.5497, 0.6027],
         [0.5964, 0.2188, 0.8984, 0.1508]]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) #, colour channels (R,G,B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and Onces


In [ ]:
#Create a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create a tensor of all onces
ones=torch.ones(size=(2,3,4))
ones


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
#Tipo de datos
ones.dtype

torch.float32

## Create a range of tensors


In [ ]:
# Use torc.arange()
one_to_ten=torch.arange(start=0,end=10,step=1)
one_to_ten


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Create tensors li ke, in the sense that it will create zeros in the same dimensions!
ten_zeros=torch.zerosos_like(input=one_to_ten)
ten_zeros

AttributeError: ignored

## Tensor Datatype

Standard error:

1. Not same dtype tensors
2. Not right shape tensors
3. Tensors not on the right device (cuda,cpu,gpu,...)

In [ ]:
#Float 32 tensor is default
float_32_tensor=torch.tensor([3,5,9],dtype=None,
                             device=None,
                             requires_grad=False # This is basically if you want pytorch to track the gradients or not!
                             )
float_32_tensor

tensor([3, 5, 9])

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16) #or half if you want
float_16_tensor

tensor([3., 5., 9.], dtype=torch.float16)

In [ ]:
#It will reduce the dtype to the smallest!
float_32_tensor*float_16_tensor

tensor([ 9., 25., 81.], dtype=torch.float16)

## Getting information from tensors

1. Tensors datatype->tensor.dtype
2. Tensors shape->tensor.shape
3. Tensors device->tensor.device

In [ ]:
# Some tensor
some_tensor = torch.rand(3,3,3)
print(some_tensor)
print(f'"ndim>",{some_tensor.ndim}, "shape>",{some_tensor.shape},"device>", {some_tensor.device}')

tensor([[[0.2967, 0.6074, 0.4962],
         [0.0274, 0.5121, 0.8637],
         [0.3820, 0.8658, 0.8356]],

        [[0.0157, 0.9241, 0.7358],
         [0.5853, 0.5590, 0.7791],
         [0.7188, 0.5470, 0.8544]],

        [[0.9154, 0.4978, 0.3604],
         [0.2124, 0.0113, 0.7832],
         [0.4703, 0.2477, 0.5101]]])
"ndim>",3, "shape>",torch.Size([3, 3, 3]),"device>", cpu


## Manipulating Tensors

Tensor operatiosn:

* Addition
* Substraction
* Multiplication
* Division
* Matrix Multiplication


In [ ]:
# Create a tennsor
tensor = torch.tensor([1,2,3])

In [ ]:
# Addition/substraction
tensor + 10, tensor-10

(tensor([11, 12, 13]), tensor([-9, -8, -7]))

In [ ]:
# Multiplicaction/division
tensor*10,tensor/10

(tensor([10, 20, 30]), tensor([0.1000, 0.2000, 0.3000]))

## Matrix Multiplication

There are two main ways to do multiplications in neural networks and deep learning:

1. Elements-wise multiplication
2. Matrix multiplication/dot product

In [ ]:
# Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals",{tensor*tensor})

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals {tensor([1, 4, 9])}


In [ ]:
# Matrix multiplication> 1*1+2*2+3*3. In this case, since we got only
# dim 1 tensors, we perform the standard dot product.
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
#time diference between matmul vs for loop
#For loop
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 3.36 ms, sys: 56 µs, total: 3.42 ms
Wall time: 4.5 ms


In [ ]:
# Pytorch matmul
%%time
tensor @ tensor

CPU times: user 159 µs, sys: 25 µs, total: 184 µs
Wall time: 193 µs


tensor(14)

## One of the most common errors in deep learning: Shape errors

### Rules that matrix multiplication must satisfy:

1. The **inner dimensions** must match:
* "(3,**2**) @ (**3**,2)" will not work
* "(2,**3**) @ (**3**,2)" will work
* "(3,**2**) @ (**2**,3)" will work
2. The resulting matrix has the shape of the **outer dimensions**:
* None
* (2,2)
* (3,3)

In [ ]:
# Error
torch.matmul(torch.rand(3,2),torch.rand(3,2))

RuntimeError: ignored

In [ ]:
print(torch.matmul(torch.rand(2,3),torch.rand(3,2)).shape)
print(torch.matmul(torch.rand(3,2),torch.rand(2,3)).shape)

torch.Size([2, 2])
torch.Size([3, 3])


In [ ]:
tensor_A=torch.rand(3,2)
tensor_B=torch.rand(3,2)
print(tensor_A)
print(tensor_B)

tensor([[0.1615, 0.1728],
        [0.2938, 0.8816],
        [0.6413, 0.4149]])
tensor([[0.9881, 0.8045],
        [0.0027, 0.4668],
        [0.2017, 0.2565]])


In [ ]:
torch.mm(tensor_A,tensor_B)

RuntimeError: ignored

In [ ]:
# Transpose of a tensor.
tensor_B.T,tensor_B.T.shapedd

In [ ]:
torch.mm(tensor_A,tensor_B.T)

## Finding min,max,mean,sum,etc (tensor aggregation)

In [ ]:
#Tensor
x=torch.arange(0,100,7)
x

tensor([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [ ]:
torch.min(x),torch.max(x) #ot x.min(), x.max()

(tensor(0), tensor(98))

In [ ]:
# Note- troch.mean() does not like int62!
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(49.), tensor(49.))

In [ ]:
torch.sum(x),x.sum()

(tensor(735), tensor(735))

## Finding the positional min and max

In [ ]:
x

tensor([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [ ]:
# Find the POSITION in the tensor that has the minimum/maximum value.
# It returns the POSITION where this is so.
x.argmin(), x.argmax()

(tensor(0), tensor(14))

## Reshaping, stacking, squeezing and usqueezing tensors

* Reshaping - reshape an input tensor to a defined shape. Just multiply all dimensions of the given tensor. Any other tensor of dimensions such that multiplied can generate the same number is legit.
* View - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor.
* Stacking (torch.stack)- combine multiple tensors on a certain direction:
  1. torch.stack: We must specify the dimension of the stack
  2. torch.vstack: Combine tensors on top of each other
  3. torch.hstack: Combine tensors side by side
* Squeeze - remove all "1" dimensions from a tensor. I guess is equivalent to *x in some cases.
* Unsqueeze - add a "1" dimension to a target tensor.
* Permute - Return a view of the input tensor with dimensions permuted (swaped) in a certain way.

In [ ]:
# Tensor
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshape=x.reshape(1,9)
x_reshape

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [ ]:
# Change the view. This is the same as before, the diference here is that
# z shares the memory with x, hence if we where to chage z, we will be chaning
# x as well!
z=x.view(1,9)
z,z.shape

(tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [ ]:
#  Squeeze
x_reshape,x_reshape.shape

(tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshape.squeeze(),x_reshape.squeeze().shape

(tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]), torch.Size([9]))

In [ ]:
# torch.unsqueeze()- adds a single dimension to a target tensor at a specific dim
x_reshape,x_reshape.shape

(tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Just note that dim=0, is 1, dim=2, is 9, hence if we unsqueeze at dim=2, we
# add a new element in dim=3!
x_reshape.unsqueeze(dim=2),x_reshape.unsqueeze(dim=2).shape

(tensor([[[5.],
          [2.],
          [3.],
          [5.],
          [5.],
          [6.],
          [5.],
          [8.],
          [9.]]]),
 torch.Size([1, 9, 1]))

In [ ]:
# permute> Basically change the order of the dimensions!!!
x=torch.rand(2,3,5)
x.size()

torch.Size([2, 3, 5])

In [ ]:
x.permute(2,0,1).size()

torch.Size([5, 2, 3])

In [ ]:
# Example usage
x_original=torch.rand(size=(224,224,3)) # [height,width,colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifst axis 0->!, 1->2, 2->0
x_original.shape,x_permuted.shape # [colour_channels,height,width]

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Indexing

Similiar to NumPy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# Indexing dim 0
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Indexing dim 1
x[0]

tensor([1, 2, 3])

In [ ]:
# Indexing dim 2
x[0][0][0] #Equivalente a [0,0,0]

tensor(1)

In [ ]:
# Get number 9
x[0,2,2]

tensor(9)

In [ ]:
# You can also use : to get all values along a certain dimension.
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Return 3,6,9
x[0,:,2]

tensor([3, 6, 9])

## PyTorch tensors and NumPy

NumPy and PyTorch has interactivity between both!
* Data in NumPy, want it in PyTorch -> torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [ ]:
# Numpy to tensor
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # Warning, Numpy datatype is float64, but torch is float32!
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of the array, what about the tensor?-> Nothing!
array = array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor?-> Nothing
tensor  = tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability (Not so random anymore!)

In short, a Neuro-Network works:

Start with random numbers -> tensor operations -> update random numbers to try make a better representation of the data -> repeat X times.

Now, we just need to set always the same random numbers for reproducability ->
 SET A SEED!


In [ ]:
import torch

# Random seed
RANDOM_SEED = 421

torch.manual_seed(RANDOM_SEED)

random_tensor_A = torch.rand(4,4)
random_tensor_B = torch.rand(4,4)
random_tensor_A,random_tensor_B


(tensor([[0.7922, 0.7083, 0.6476, 0.6543],
         [0.4064, 0.1594, 0.0502, 0.0978],
         [0.8457, 0.2765, 0.4336, 0.4304],
         [0.2362, 0.6191, 0.1080, 0.4302]]),
 tensor([[0.2889, 0.1024, 0.2511, 0.1389],
         [0.8709, 0.0666, 0.9914, 0.7850],
         [0.1112, 0.9797, 0.6787, 0.7027],
         [0.8692, 0.5954, 0.8845, 0.2581]]))

## Running tensors and PyTorch on same GPU (faster computation!)

GPUs = faster computation on numbers thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good.

### 1. Getting a GPU

1. Easy - Google Colab (!nvidia-smi)
2. Use own GPU - takes a setup + lots of options-> [good resource](https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/)
3. Cloud Computing -> Rent computer on cloud> GCP, AWS, Azure

## Check GPU access with PyTorch

In [ ]:
# Check for GPU access to PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Set Device Agnostic Code> Basically, if there is a GPU, make PyTorch use it!
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count the number of GPUs
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

Using GPU does faster computations!

In [ ]:
# Create a tensor> default is on cpu
tensor = torch.tensor([1,2,3])
tensor,tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
# Move tensor de GPU (if exists). Note> 0 Represent that we are on the GPU 1!
tensor_to_gpu = tensor.to(device)
tensor_to_gpu

tensor([1, 2, 3], device='cuda:0')

## Move tensor back to CPU

In [ ]:
# Numpy does not operate on the cpu!
#tensor_to_gpu.numpy() # Wont work
# Fix the issue!
tensor_back_on_CPU = tensor_to_gpu.cpu().numpy()


## [Excercises](https://www.learnpytorch.io/00_pytorch_fundamentals/)